build:
  image: golang:1.4.2
  environment:
    - GOPATH=/drone
  commands:
    - go get
    - go build
    - go test

plugin:
  name: Slack
  desc: Sends build status notifications to your Slack channel.
  type: notify
  image: plugins/drone-slack
  labels:
    - chat
    - messaging

  
