build:
  image: drone/golang
  environment:
    - CGO_ENABLED=0
    - GOPATH=/drone
  commands:
    - go get
    - go build
    - go test

publish:
  docker:
    username: drone
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-slack
    when:
      branch: master

plugin:
  name: Slack
  desc: Send build status notifications to your Slack channel.
  type: notify
  image: plugins/drone-slack
  labels:
    - chat
    - messaging
