pipeline:
  test:
    image: golang:1.6
    environment:
      - CGO_ENABLED=0
      - GOPATH=/drone
    commands:
      - make vet
      - make build
      - make test
  docker:
    storage_driver: overlay
    repo: plugins/drone-slack
    tag: [ "latest" ]
    when:
      branch: release/0.4
      event: push

plugin:
  name: Slack
  desc: Send build status notifications via Slack
  type: notify
  image: plugins/drone-slack
  labels:
    - chat
    - messaging
