build:
  image: golang:1.4.2
  environment:
    - CGO_ENABLED=0
    - GOPATH=/drone
  commands:
    - go get
    - CGO_ENABLED=0 go build -a -tags netgo
    - go test

publish:
  docker:
    username: $$DOCKER_USER
    password: $$DOCKER_PASS
    email: $$DOCKER_EMAIL
    repo: plugins/drone-slack
    when:
      branch: master

notify:
  slack:
    webhook_url: $$SLACK_URL
    channel: #dev
    username: drone

plugin:
  name: Slack
  desc: Sends build status notifications to your Slack channel.
  type: notify
  image: plugins/drone-slack
  labels:
    - chat
    - messaging
